
export const SET_FROM_AMOUNT = "SET_FROM_AMOUNT";

export const SET_TO_CURRENCY_TYPE = "SET_TO_CURRENCY_TYPE";

export const SET_FROM_CURRENCY_TYPE= "SET_FROM_CURRENCY_TYPE";

export const SET_EXCHANGE_RATES = "SET_EXCHANGE_RATES";

export const TOGGLE_DISCLAIMER = "TOGGLE_DISCLAIMER";